/**
 * Google Gemini AI Integration
 * Generates achievement summaries from GitHub and LeetCode data
 */

import fetch from 'node-fetch';

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';
const MODEL = 'gemini-1.5-flash'; // Using stable version instead of 2.5-flash

/**
 * Call Gemini API with retry logic
 * @param {string} prompt - Input prompt
 * @param {number} retries - Number of retries
 * @returns {Promise<string>} Generated text
 */
async function callGemini(prompt, retries = 3) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  const url = `${GEMINI_API_BASE}/${MODEL}:generateContent?key=${apiKey}`;

  for (let i = 0; i < retries; i++) {
    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 2048,
            candidateCount: 1
          }
        })
      });

      if (!response.ok) {
        const error = await response.text();
        throw new Error(`Gemini API error: ${response.status} - ${error}`);
      }

      const data = await response.json();
      
      // Handle different response formats
      if (data.candidates && data.candidates.length > 0) {
        const candidate = data.candidates[0];
        if (candidate.content && candidate.content.parts && candidate.content.parts.length > 0) {
          return candidate.content.parts[0].text;
        }
      }

      // Log the response for debugging (only if no content found)
      console.warn('⚠️  Gemini returned no content, using fallback');
      throw new Error('No content generated by Gemini');
    } catch (error) {
      console.error(`❌ Gemini API attempt ${i + 1} failed:`, error.message);
      
      if (i === retries - 1) {
        // On final retry, throw error to use fallback data
        throw error;
      }

      // Wait before retrying (exponential backoff)
      await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, i)));
    }
  }
}

/**
 * Generate achievements from GitHub and LeetCode data
 * @param {Object} githubData - GitHub stats and repos
 * @param {Object} leetcodeData - LeetCode stats
 * @returns {Promise<Object>} Generated achievements
 */
export async function generateAchievements(githubData, leetcodeData) {
  const prompt = buildAchievementPrompt(githubData, leetcodeData);
  
  try {
    const response = await callGemini(prompt);
    return parseAchievements(response);
  } catch (error) {
    console.error('❌ Error generating achievements:', error.message);
    throw error;
  }
}

/**
 * Build achievement generation prompt
 * @param {Object} githubData - GitHub data
 * @param {Object} leetcodeData - LeetCode data
 * @returns {string} Formatted prompt
 */
function buildAchievementPrompt(githubData, leetcodeData) {
  const { repos, contributions, stats, topLanguages } = githubData;
  const recentRepos = repos.slice(0, 5);

  return `You are a professional resume writer. Based on the following developer's coding activity, generate a concise professional summary and 3-5 achievement bullet points.

## GitHub Activity:
- Total Repositories: ${repos.length}
- Total Contributions (12 months): ${contributions.totalContributions}
- Followers: ${stats.followers}
- Top Languages: ${topLanguages.map(l => l.language).join(', ')}

## Recent Projects:
${recentRepos.map(r => `- ${r.name}: ${r.description || 'No description'} (${r.language || 'N/A'}) - ${r.stars} stars`).join('\n')}

## LeetCode Stats:
- Total Problems Solved: ${leetcodeData.totalSolved}
- Easy: ${leetcodeData.easySolved}/${leetcodeData.easyTotal}
- Medium: ${leetcodeData.mediumSolved}/${leetcodeData.mediumTotal}
- Hard: ${leetcodeData.hardSolved}/${leetcodeData.hardTotal}
${leetcodeData.ranking ? `- Global Ranking: ${leetcodeData.ranking.toLocaleString()}` : ''}

## Instructions:
1. Write a 2-3 sentence professional summary highlighting key accomplishments
2. Generate 3-5 bullet points (each 1-2 lines) describing:
   - Technical achievements
   - Project milestones
   - Problem-solving capabilities
   - Growth and learning

## Format (respond ONLY in this JSON format):
{
  "summary": "2-3 sentence professional summary",
  "bulletPoints": [
    "First achievement",
    "Second achievement",
    "Third achievement"
  ]
}

Keep it professional, quantifiable, and resume-appropriate. Focus on impact and technical skills.`;
}

/**
 * Parse Gemini response into structured achievements
 * @param {string} response - Raw Gemini response
 * @returns {Object} Parsed achievements
 */
function parseAchievements(response) {
  try {
    // Try to extract JSON from response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        summary: parsed.summary || '',
        bulletPoints: parsed.bulletPoints || [],
        generatedAt: new Date().toISOString()
      };
    }

    // Fallback parsing if not JSON
    const lines = response.split('\n').filter(line => line.trim());
    const bulletPoints = lines
      .filter(line => line.trim().startsWith('-') || line.trim().startsWith('•'))
      .map(line => line.trim().replace(/^[-•]\s*/, ''))
      .slice(0, 5);

    const summary = lines
      .filter(line => !line.trim().startsWith('-') && !line.trim().startsWith('•'))
      .join(' ')
      .slice(0, 300);

    return {
      summary: summary || 'Actively contributing to open-source projects and solving algorithmic challenges.',
      bulletPoints: bulletPoints.length > 0 ? bulletPoints : [
        'Developed and maintained multiple full-stack applications',
        'Consistently solving algorithmic problems to strengthen problem-solving skills',
        'Contributing to open-source projects and collaborating with the developer community'
      ],
      generatedAt: new Date().toISOString()
    };
  } catch (error) {
    console.error('❌ Error parsing achievements:', error.message);
    return {
      summary: 'Actively contributing to open-source projects and solving algorithmic challenges.',
      bulletPoints: [
        'Developed and maintained multiple full-stack applications',
        'Consistently solving algorithmic problems to strengthen problem-solving skills',
        'Contributing to open-source projects and collaborating with the developer community'
      ],
      generatedAt: new Date().toISOString()
    };
  }
}

/**
 * Generate a short bio for hero section
 * @param {Object} githubData - GitHub data
 * @param {Object} leetcodeData - LeetCode data
 * @returns {Promise<string>} Generated bio
 */
export async function generateBio(githubData, leetcodeData) {
  const { topLanguages, stats } = githubData;

  const prompt = `Write a single engaging sentence (max 20 words) for a developer's portfolio hero section.

Context:
- ${stats.publicRepos} public repositories
- Top skills: ${topLanguages.slice(0, 3).map(l => l.language).join(', ')}
- ${leetcodeData.totalSolved} LeetCode problems solved

Make it punchy, professional, and highlight both building and problem-solving. Do NOT use quotes or markdown.`;

  try {
    const response = await callGemini(prompt);
    return response.trim().replace(/["']/g, '');
  } catch (error) {
    console.error('❌ Error generating bio:', error.message);
    return 'Full-stack developer passionate about building scalable applications and solving complex problems.';
  }
}
